---
title: "P8105_hw2_ykk2116"
author: "Yaa Klu"
date: "10/1/2018"
output: html_document
---

### Problem 1

Accessing data file. Reading and cleaning dataset
```{r}

library(tidyverse) 


nyc_subway = read_csv(file =  "./data/NYC_Transit_Subway_Entrance_And_Exit_Data (1).csv") %>%
janitor::clean_names() %>%
select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>%
mutate(entry = recode(entry, "YES"= TRUE, "NO" = FALSE))
 
```


```{r}
unique_stations = distinct(nyc_subway, line, station_name, ada)

nrow(unique_stations)

sum(unique_stations$ada)

```


```{r}

entry_vending = nyc_subway %>%
mutate(vending = recode(vending, "YES" = TRUE, "NO" = FALSE),
       entry_no_vending = !(vending == entry))
sum(entry_vending$entry_no_vending)/nrow(entry_vending)       
       
```



```{r}

reformatted_nyc_subway = nyc_subway %>%
  gather(key = route, value = train, route1:route11) %>%
  separate(route, into = c("remove1", "route"), sep = 5) %>%
  select(everything(), -remove1) %>% 
  distinct(line, station_name, train, ada) %>% 
  filter(train == "A")
 
nrow(reformatted_nyc_subway)

sum(reformatted_nyc_subway$ada)

```

### Problem 2

```{r}

trash_wheel = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N258") %>%
janitor::clean_names(dat = .) %>%
  filter(!is.na(dumpster)) %>%
  mutate(sports_balls = as.integer(sports_balls))

```


Importing and cleaning 2016 and 2017 precipitation data
```{r}
precipitation_2016 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2016 Precipitation", range = "A2:B14") %>%
  janitor::clean_names(dat = .) %>%
  mutate(year = 2016) 

precipitation_2017 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2017 Precipitation", range = "A2:B14") %>%  
  janitor::clean_names(dat = .) %>%
  mutate(year = 2017) %>%
    filter(!is.na(total))
```




